---
- hosts: linux
  tasks:
  - name: print output messages
     command: echo1 "i am in training"
     register: output
  - debug: msg="standard output={{output.stdout}}"
  - debug: msg="standard error={{output.stderr}}"
